apiVersion: v1
kind: Service
metadata:
  name: fiap-doctor-service
spec:
  selector:
    app: fiap-doctor
  type: LoadBalancer  # Para expor o serviço externamente
  ports:
    - protocol: TCP
      port: 80           # Porta acessível externamente
      targetPort: 8080    # Porta usada pelo container
